### ISSUE TITLE
data_list = soup.find_all('div', 'articleh') 返回为空值

### ISSUE THREAD

**Issue by c976237222** [Euclid-Jie/Euclidguba-search#2]
您好,非常感谢分享代码,
请问data_list[self.num_start:] 为空值是怎么回事呢

**Comment by Euclid-Jie** [comment]
> 您好,非常感谢分享代码,
> 请问data_list[self.num_start:] 为空值是怎么回事呢

网站结构可能变化了，晚上我看一下
