### ISSUE TITLE
有可能网站结构又进行了变化

### ISSUE THREAD

**Issue by c976237222** [Euclid-Jie/Euclidguba-search#3]
get_soup_form_url 的soup返回值不符合程序要求

**Comment by Euclid-Jie** [comment]
> get_soup_form_url 的soup返回值不符合程序要求

收到，我晚上处理一下

**Comment by c976237222** [comment]
> > get_soup_form_url 的soup返回值不符合程序要求
> 
> 收到，我晚上处理一下

谢谢同学  方便加您个微信吗

**Comment by Euclid-Jie** [comment]
修复好了

**Comment by c976237222** [comment]
> 修复好了

谢谢
