### ISSUE TITLE
爬虫结束后，文件夹里没有csv或者db文件

### ISSUE THREAD

**Issue by Vincenteage** [Euclid-Jie/Euclidguba-search#4]
![image](https://github.com/Euclid-Jie/Euclidguba-search/assets/13411542/5f9dfee6-84b8-4264-9f8e-19848e009794)

**Comment by Euclid-Jie** [comment]
设置代理了吗

**Comment by Euclid-Jie** [comment]
> ![image](https://github.com/Euclid-Jie/Euclidguba-search/assets/13411542/5f9dfee6-84b8-4264-9f8e-19848e009794)
> 

把你的具体参数发一下吧，我需要先复现error

**Comment by Vincenteage** [comment]
![image](https://github.com/Euclid-Jie/Euclidguba-search/assets/13411542/137dd25a-46e3-48a7-8c79-26305b00ac30)
![image](https://github.com/Euclid-Jie/Euclidguba-search/assets/13411542/cce36199-f773-4d58-95af-9ddec8137dcf)
我目前只爬了两页的内容，没挂代理。参数我只改了如图所示的两处，即开头的“MongoDB=False”，和最后的股票代码和页数的设置：demo = guba_comments('002594', pages_start=1, pages_end=3, num_start=0, MongoDB=False)。
PS：我不会编程，还是在您的文档说明和chatgpt的帮助下勉强看懂了代码，自己尝试修改的以上两处，不知道修改的是否符合规范。

**Comment by Euclid-Jie** [comment]
暂时看起来没什么问题
等我晚上下班，回家给你看看

**Comment by Vincenteage** [comment]
好嘞，提前谢谢您！

**Comment by Vincenteage** [comment]
![image](https://github.com/Euclid-Jie/Euclidguba-search/assets/13411542/9c688bed-d1bb-479a-ba2b-94ccd07a0f21)
![image](https://github.com/Euclid-Jie/Euclidguba-search/assets/13411542/f716d7d2-fb5a-4010-9064-ceb8c3acd5e8)
![image](https://github.com/Euclid-Jie/Euclidguba-search/assets/13411542/d58a88c6-eb71-4b5d-b1a5-8fc771d29965)
现在出现了另一个问题，把参数改为如上图所示后，运行后报错，截图如下
![image](https://github.com/Euclid-Jie/Euclidguba-search/assets/13411542/898115f5-8b39-4e22-8c2b-96148912f90d)

**Comment by Euclid-Jie** [comment]
这很可能是网页改动，我才下班，晚点看

**Comment by Vincenteage** [comment]
![image](https://github.com/Euclid-Jie/Euclidguba-search/assets/13411542/4336b698-caaf-44dd-a73f-60bad3e44ee7)
刚吃个饭回来，代码没做任何改动，运行后结果又变了，如上图所示。
下午时如上一条反馈的图所示，会依次显示page100, page101, ...page104的进度，这种情况下，在文件夹里有输出的csv文件（虽然爬取不全，设置爬取三四页，实际只有不到30条数据，一页的量都不够）；
现在则如上图所示，无视我设置的起始和终止页数，只显示page1，直到进度结束，而且结束后在文件夹里没有输出的csv文件。

此外，我发现如果起始页数不从第一页开始，比如从49页开始，则爬取的页数如果超过3页左右，运行起来就不会报错。
我下午设置起始49页，终止页数55，就会如上一条反馈的图一样报错；如果设置终止页数52，则不会报错，但输出的csv文件往往只有两三行信息，最多时也不超过30条。

**Comment by Vincenteage** [comment]
![image](https://github.com/Euclid-Jie/Euclidguba-search/assets/13411542/4b3d0c73-1872-4ca3-94df-8912718d638e)
上一条的判断是错的，即使这样依次page2, page3, page4显示出来，现在也没有生成的csv文件了。这次依然只改了起止页数，把软件重启了下，就变成这样了。

**Comment by Euclid-Jie** [comment]
我测试了，程序没问题，可以正常爬取到数据
我的建议是你开代理，我在readme中有写
![image](https://github.com/Euclid-Jie/Euclidguba-search/assets/71357995/037de522-b173-4463-927c-226e2b729578)

**Comment by Euclid-Jie** [comment]
如果你数据量不大的话，我也可以帮你爬了

**Comment by Vincenteage** [comment]
我想爬科大讯飞2022年全年的数据，写毕业论文可能要用。昨天我去您主页推荐的那个代理网站都注册好了，看还需要实名认证就有点犹豫。而且原本想的是先试试这程序能正常运行再开代理不迟。请问您如果帮我爬这个数据的话，大概需要多少钱？
顺便问下，您是否有对爬下来的csv文件里的数据进行过重复筛选，我昨天偶尔有几次成功爬取，刚打开文件时也是几千条，然而用excel重复筛选后，就只剩80条了。

**Comment by Euclid-Jie** [comment]
趁午休时间帮你爬上了，到时候你把代理费用给我就行

**Comment by Euclid-Jie** [comment]
> 我想爬科大讯飞2022年全年的数据，写毕业论文可能要用。昨天我去您主页推荐的那个代理网站都注册好了，看还需要实名认证就有点犹豫。而且原本想的是先试试这程序能正常运行再开代理不迟。请问您如果帮我爬这个数据的话，大概需要多少钱？
> 顺便问下，您是否有对爬下来的csv文件里的数据进行过重复筛选，我昨天偶尔有几次成功爬取，刚打开文件时也是几千条，然而用excel重复筛选后，就只剩80条了。

加我QQ吧，2379938684

**Comment by Vincenteage** [comment]
太感谢您了！已发送好友请求，请通过下~

**Comment by Euclid-Jie** [comment]
> 太感谢您了！已发送好友请求，请通过下~

真尴尬，QQ账号写错了
2379928684

**Comment by Vincenteage** [comment]
抱歉现在才看到回复。
哈哈好好的，我重新发了好友请求。
