### ISSUE TITLE
采用旧代码不会报错但也没结果

### ISSUE THREAD

**Issue by WongProphecy** [Euclid-Jie/Euclidguba-search#5]
你好，在原来版本的代码中，不管我股票代码写什么，跟股票名称对不对的上，代理随便填什么都能正常跑，但是都没有结果这是为什么呢？我原本只修改了main中的相关参数，就是这两串代码：demo = guba_comments('601985', pages_start=1321, pages_end=1480, MongoDB=True)以及
proxies = {'http': 'http://y889.kdltps.com:15818', 'https': 'http://y889.kdltps.com:15818'}
也申请了[易代理]，然后就跑main_class这一个文件，没有结果……
<img width="1262" alt="Pasted Graphic" src="https://github.com/Euclid-Jie/Euclidguba-search/assets/163408824/446eb776-f777-4fb8-a7cb-e333cd5af985">

**Comment by Euclid-Jie** [comment]
@WongProphecy  感谢您的反馈，从你的截图来看，推荐你检查以下两点：
- 你的股票代码是2611，对应的是东方精工，并不是贵州茅台
- `pages_start` 和 `pages_end` 对应的是第几页的帖子，而对于东方精工来说并没有2000~2010页
![image](https://github.com/Euclid-Jie/Euclidguba-search/assets/71357995/8fbc2761-97d0-451f-9a89-b0e7d603481b)

我推荐的做法是：
- 确认你需要的股票`secCode`，并与`collectionName`相对应，这将利于你检查是否存储文件
- 根据具体股票的发帖情况，以及你想要的时间区间，合理设置`pages_start` 和`pages_end`
