### ISSUE TITLE
关于代理服务器的问题

### ISSUE THREAD

**Issue by xingrui-zhang** [Euclid-Jie/Euclidguba-search#6]
您好
"代理服务器域名网址，端口，推荐使用：[易代理](https://www.kuaidaili.com/?ref=mes9ujq5wnrn)，隧道代理按量计费一小时1元钱"
这好像是快代理的网址
另外如何设置代理服务器域名网址，端口呢，我付费了之后从哪里能够得到这个proxies内的网址内容呢，谢谢您
如果可以的话能否加QQ或者WX进一步交流，谢谢您

**Comment by xingrui-zhang** [comment]
另外就是它将数据保存到了哪里，还是我需要先新建一个csv文件才能保存？

**Comment by Euclid-Jie** [comment]
> 另外就是它将数据保存到了哪里，还是我需要先新建一个csv文件才能保存？

不需要新建，会自动创建

**Comment by xingrui-zhang** [comment]
是直接创建到当前目录下吗？

**Comment by Euclid-Jie** [comment]
> 您好 "代理服务器域名网址，端口，推荐使用：[易代理](https://www.kuaidaili.com/?ref=mes9ujq5wnrn)，隧道代理按量计费一小时1元钱" 这好像是快代理的网址 另外如何设置代理服务器域名网址，端口呢，我付费了之后从哪里能够得到这个proxies内的网址内容呢，谢谢您 如果可以的话能否加QQ或者WX进一步交流，谢谢您

感谢，我将修改，付费后会得到网址和端口

**Comment by Euclid-Jie** [comment]
> 是直接创建到当前目录下吗？

会在./guba/ **.csv

**Comment by xingrui-zhang** [comment]
![屏幕截图 2024-03-16 175005](https://github.com/Euclid-Jie/Euclidguba-search/assets/137508649/64405a28-2235-4de1-a5b4-0e0566a82b9f)
这个可以吗？

**Comment by Euclid-Jie** [comment]
> ![屏幕截图 2024-03-16 175005](https://private-user-images.githubusercontent.com/137508649/313394732-64405a28-2235-4de1-a5b4-0e0566a82b9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1ODI5MzksIm5iZiI6MTcxMDU4MjYzOSwicGF0aCI6Ii8xMzc1MDg2NDkvMzEzMzk0NzMyLTY0NDA1YTI4LTIyMzUtNGRlMS1hNWI0LTBlMDU2NmE4MmI5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQwOTUwMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDcyN2ZkYjk1Yzc1OTlhMjUwYzVkODlmYzNmOWM0YWU0MzI0M2E2OTU5ZWM3Y2I4MmE2NzYzOWE1ZGI3ODk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UMghOl6x7lwpDUtozpa3dOrxwVC7n_uvvPvqm8eWl7c) 这个可以吗？

可以

**Comment by Euclid-Jie** [comment]
> 您好 "代理服务器域名网址，端口，推荐使用：[易代理](https://www.kuaidaili.com/?ref=mes9ujq5wnrn)，隧道代理按量计费一小时1元钱" 这好像是快代理的网址 另外如何设置代理服务器域名网址，端口呢，我付费了之后从哪里能够得到这个proxies内的网址内容呢，谢谢您 如果可以的话能否加QQ或者WX进一步交流，谢谢您
QQ：2379928684，如有需要可联系
